<a href="https://colab.research.google.com/github/mayuravaani/AI/blob/preprocessing/PreProcess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from sklearn import preprocessing

In [4]:
Input_data = np.array([[2.1, -1.9, 5.5], [-1.5, 2.4, 3.5], [0.5, -7.9, 5.6], [5.9, 2.3, -5.8]])

Technique for preprocessing
* Binarization
* Mean Removal
* Scaling
* Normalization

Binarization: when we need to convert numerical value into boolean value;

In [8]:
data_binarized = preprocessing.Binarizer(threshold=0.5).transform(Input_data)
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]
