<a href="https://colab.research.google.com/github/mayuravaani/AI/blob/preprocessing/PreProcess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from sklearn import preprocessing

In [4]:
Input_data = np.array([[2.1, -1.9, 5.5], [-1.5, 2.4, 3.5], [0.5, -7.9, 5.6], [5.9, 2.3, -5.8]])

Technique for preprocessing
* Binarization
* Mean Removal
* Scaling
* Normalization

Binarization: when we need to convert numerical value into boolean value;

In [8]:
data_binarized = preprocessing.Binarizer(threshold=0.5).transform(Input_data)
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


Mean Removal: Basically it is used to eliminate the mean from feature vector so that every feature is centered on zero. 

In [14]:
print("Mean =", Input_data.mean(axis=0))
print("Std deviation =", Input_data.std(axis=0))
print("Mean =", Input_data.mean())
print("Std deviation =", Input_data.std())

Mean = [ 1.75  -1.275  2.2  ]
Std deviation = [2.71431391 4.20022321 4.69414529]
Mean = 0.8916666666666666
Std deviation = 4.249991830057507
